import type { Metadata } from 'next'

/**
 * Per-couple layout. Exists only to wire the dynamic favicon — every
 * route under `/[slug]/...` (the public invitation AND the dashboard)
 * inherits the icon link declared here.
 *
 * The icon itself is generated by `app/[slug]/icon/route.ts` as SVG.
 */
export async function generateMetadata(
  { params }: { params: { slug: string } },
): Promise<Metadata> {
  return {
    icons: {
      icon: [{ url: `/${params.slug}/icon`, type: 'image/svg+xml' }],
    },
  }
}

export default function SlugLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
